# Generated by Django 5.1.4 on 2025-01-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamento',
            name='objeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.objeto'),
        ),
    ]
